# Python NumPy 

# Create 1D Array Using Conversion Method list as np.array

In [1]:
import numpy as np

In [2]:
Arr1 = np.array([1,2,3,4,5,6,7])

In [3]:
Arr1

array([1, 2, 3, 4, 5, 6, 7])

# Create 2D Array

In [4]:
Arr2 = np.array([[1,2,3],[2,4,5],[4,2,0]])

In [5]:
Arr2

array([[1, 2, 3],
       [2, 4, 5],
       [4, 2, 0]])

# Attributes

In [6]:
Arr2.dtype

dtype('int32')

In [7]:
Arr2.shape

(3, 3)

In [8]:
Arr2.size

9

In [9]:
Arr1.size

7

# Access Array Index

In [ ]:
Arr1[3]

4

In [ ]:
#for 2d array 
Arr2[0,2]

In [ ]:
Arr2[1,1]

# Change Element in Array

In [ ]:
Arr1[2] = 45

In [ ]:
Arr1

In [ ]:
Arr2[0,2] = 44

In [16]:
Arr2

# Define dtype (Data Type)

In [17]:
Array = np.array([2,3,4,66,7], np.int8)

In [18]:
Array

array([ 2,  3,  4, 66,  7], dtype=int8)

In [19]:
# we Cannot store big value in dtype int8
Array1 = np.array([2,3,4,6666666,7], np.int8)

C:\Users\OmiTech27\AppData\Local\Temp\ipykernel_18316\1197044741.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 6666666 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  Array1 = np.array([2,3,4,6666666,7], np.int8)


In [20]:
Array1 = np.array([2,3,4,6666666,7], np.int32)

In [21]:
Array1

array([      2,       3,       4, 6666666,       7])

# Methods in Numpy

In [22]:
#calculation of 2 Array
arr = np.array([[1,2,3],[2,4,5],[4,2,0]])

In [23]:
arr1 = np.array([[2,3,3],[3,5,3],[1,2,0]])

In [24]:
arr + arr1

array([[3, 5, 6],
       [5, 9, 8],
       [5, 4, 0]])

In [25]:
arr * arr1

array([[ 2,  6,  9],
       [ 6, 20, 15],
       [ 4,  4,  0]])

In [26]:
arr - arr1

array([[-1, -1,  0],
       [-1, -1,  2],
       [ 3,  0,  0]])

# Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)

In [27]:
Arr_arange = np.arange(5)

In [28]:
Arr_arange

array([0, 1, 2, 3, 4])

In [29]:
Arr_arange1= np.arange(1,4)

In [30]:
Arr_arange1

array([1, 2, 3])

In [31]:
ls = np.linspace(1,5,10)

In [32]:
ls

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
empty = np.empty((3,3)) 

In [34]:
empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.17383318e-321],
       [1.78019082e-306, 1.37959740e-306, 2.29178686e-312]])

In [35]:
emptylike = np.empty_like(ls)

In [36]:
emptylike

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [37]:
idn = np.identity((5))

In [38]:
idn

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
type(idn)

numpy.ndarray

In [40]:
idn.shape

(5, 5)

In [41]:
array = np.arange(25)

In [42]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
array.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [45]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
array = array.reshape(5,5)

In [47]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
zeros = np.zeros((3,3))

In [50]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
zeros.shape

(3, 3)

# AXIS0 AND AXIS1

In [52]:
ar = np.array([[1,2,3],[3,2,1],[3,4,5]])

In [53]:
ar

array([[1, 2, 3],
       [3, 2, 1],
       [3, 4, 5]])

In [54]:
ar.sum(axis=0)

array([7, 8, 9])

In [55]:
ar.sum(axis=1)

array([ 6,  6, 12])

# Attributes

In [56]:
#Transpose (Convert rows into colums)
ar.T

array([[1, 3, 3],
       [2, 2, 4],
       [3, 1, 5]])

In [57]:
#itarator creater
ar.flat

In [58]:
for i in ar:
    print(i)

[1 2 3]
[3 2 1]
[3 4 5]


In [59]:
for item in ar.flat:
    print(item)

1
2
3
3
2
1
3
4
5


In [60]:
# number of dimensions
ar.ndim

2

In [61]:
ar.size

9

In [62]:
ar.nbytes

36

In [63]:
ar.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Numpy Methods

In [64]:
x = np.array([2,4,6,5])

In [65]:
#max value of index
x.argmax()

2

In [66]:
#min value of index
x.argmin()

0

In [67]:
#sort array
x.argsort()

array([0, 1, 3, 2], dtype=int64)

In [68]:
#sort 2d array
ar

array([[1, 2, 3],
       [3, 2, 1],
       [3, 4, 5]])

In [69]:
ar.argmin()

0

In [70]:
ar.argmax()

8

In [71]:
ar.argmax(axis=0)

array([1, 2, 2], dtype=int64)

In [72]:
ar.argmax(axis=1)

array([2, 0, 2], dtype=int64)

In [73]:
ar.argsort()

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2]], dtype=int64)

In [74]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2]], dtype=int64)

In [75]:
ar.argsort(axis=0)

array([[0, 0, 1],
       [1, 1, 0],
       [2, 2, 2]], dtype=int64)

In [76]:
ar

array([[1, 2, 3],
       [3, 2, 1],
       [3, 4, 5]])

In [77]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.41421356, 1.        ],
       [1.73205081, 2.        , 2.23606798]])

In [78]:
ar.sum()

24

In [79]:
ar.max()

5

In [80]:
ar.min()

1

In [81]:
#find element in array
ar

array([[1, 2, 3],
       [3, 2, 1],
       [3, 4, 5]])

In [82]:
np.where(ar>3)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [83]:
np.count_nonzero(ar)

9

In [84]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

# Check Diffirence between python list vs numPy Array

In [85]:
import sys

In [86]:
pylist = [2,444,5,55,90]

In [87]:
npArray = np.array(pylist)

In [88]:
sys.getsizeof(1)* len(pylist)

140

In [89]:
npArray.itemsize* npArray.size

20